repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: tflint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--add-to-exiting-file=true
          - --hook-config=--create-file-if-not-exist=true
